### ISSUE TITLE
UnicodeDecodeError: 'gbk' codec can't decode byte 0xa6 in position 738: illegal multibyte sequence

### ISSUE THREAD

**Issue by ezxuma** [LQR471814/Quizizz-Hack#1]
Traceback (most recent call last):
  File "parser.py", line 6, in <module>
    quizInfo = json.loads(f.read())
UnicodeDecodeError: 'gbk' codec can't decode byte 0xa6 in position 738: illegal multibyte sequence

**Comment by LQR471814** [comment]
Please provide steps to reproduce.
Eg. Input file, OS

**Comment by ezxuma** [comment]
Input file : 5e929bbbcc6526001beebd6e.json 
OS : Windows 10 64 bit v1903

**Comment by LQR471814** [comment]
Oops, should've phrased that a bit better, can you provide the file as an attachment?

**Comment by AlexeyZavar** [comment]
I had the same issue with russian language. Try to specify encoding at 5 line (for example, ```f = open(filename, "r", encoding="utf-8")```)

**Comment by LQR471814** [comment]
Ok, so I specified encoding when reading the file, hopefully that fixes the problem. I'm gonna keep this thread open in case it doesn't.

**Comment by LQR471814** [comment]
It's been 6 days, I'm assuming no reply means the issue is fixed. Closing the issue!
