### ISSUE TITLE
New Quizizz API

### ISSUE THREAD

**Issue by voda505** [LQR471814/Quizizz-Hack#4]
Hey, 
Quizizz updated its API from v3 to v4. Your method should still work, according to my little progamming skills. I have no idea how to edit the parser for the new API (The .json file looks really different from what it used to). Any chance you could either tell me how I can fix it or fix the script? Or the entire method is busted, that is also an option, like I said, I dont know that much about programming. 
Any help will the really appreciated, thanks in advance.

**Comment by xNetcat** [comment]
The script still works for me. No need to change anything
