### ISSUE TITLE
empty answers file

### ISSUE THREAD

**Issue by jmikulo** [LQR471814/Quizizz-Hack#7]
sometimes generates empty file with answers

https://kurwa.club/u/8ahYJ.mp4

**Comment by xNetcat** [comment]
Your .json file contains polish characters that break the process of saving the answers to the file. 

Fixes:
- You can Remove all polish characters from the file manually
- Use this tool http://www.spolszcz.pl/usun-polskie-znaki.html
- Replace this line of code 
```python
f = open("answers.json", "w")
```
with this 
```python
f = open("answers.json", "w", encoding="utf-8")
```

**Comment by LQR471814** [comment]
Merged proposed pull request
